#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Running Husky..."
npm run prepare
echo "HUSKY INSTALLED SUCCESSFULLY"
npm run lintstaged_install
echo "LINT STAGED INSTALLED SUCCESSFULLY"
npm run precommit
echo "PRECOMMIT HOOK RAN SUCCESSFULLY"